export default {
  SET_PRODUCTS_LOADING: 'SET_PRODUCTS_LOADING',
  SET_PRODUCTS_SUCCESS: 'SET_PRODUCTS_SUCCESS',
  SET_QUANTITY: 'SET_QUANTITY',
  SET_PRODUCTS_FAIL: 'SET_PRODUCTS_FAIL',

  GET_CATEGORIES_LOADING: 'GET_CATEGORIES_LOADING',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAIL: 'GET_CATEGORIES_FAIL',

  GET_CHANGED_CATEGORY: 'GET_CHANGED_CATEGORY',
  GET_NUMBER_OF_PAGE: 'GET_NUMBER_OF_PAGE'
};
