const MIN_LENGTH_OF_REVIEWER_NAME = 3;
const MIN_LENGTH_OF_COMMENT = 30;
const MAX_LENGTH_OF_COMMENT = 1000;

export {
  MIN_LENGTH_OF_REVIEWER_NAME,
  MIN_LENGTH_OF_COMMENT,
  MAX_LENGTH_OF_COMMENT
};
