export default {
  ADD_TO_CART: 'ADD_TO_CART',
  DELETE_FROM_CART: 'DELETE_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  INCREASE_PRODUCT_QUANTITY: 'INCREASE_PRODUCT_QUANTITY',
  DECREASE_PRODUCT_QUANTITY: 'DECREASE_PRODUCT_QUANTITY',

  REQUEST_CART_LOADING: 'REQUEST_CART_LOADING',
  REQUEST_CART_SUCCESS: 'REQUEST_CART_SUCCESS',
  REQUEST_CART_FAIL: 'REQUEST_CART_FAIL',

  FIND_USER_CART_SUCCESS: 'FIND_USER_CART_SUCCESS',
  UPDATE_CART_SUCCESS: 'UPDATE_CART_SUCCESS',
  CREATE_CART_SUCCESS: 'CREATE_CART_SUCCESS'
};
