export const SET_ADDRESSES_LOADING = 'SET_ADDRESSES_LOADING';
export const SET_ADDRESSES_SUCCESS = 'SET_ADDRESSES_SUCCESS';
export const SET_ADDRESSES_FAIL = 'SET_ADDRESSES_FAIL';

export const ADD_NEW_ADDRESS_LOADING = 'ADD_NEW_ADDRESS_LOADING';
export const ADD_NEW_ADDRESS_SUCCESS = 'ADD_NEW_ADDRESS_SUCCESS';
export const ADD_NEW_ADDRESS_FAIL = 'ADD_NEW_ADDRESS_FAIL';

export const UPDATE_ADDRESS_LOADING = 'UPDATE_ADDRESS_LOADING';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_FAIL = 'UPDATE_ADDRESS_FAIL';

export const DELETE_ADDRESS_LOADING = 'DELETE_ADDRESS_LOADING';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAIL = 'DELETE_ADDRESS_FAIL';
