export const REGISTER_USER_LOADING = 'REGISTER_USER_LOADING ';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING ';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const SET_USER_INFO_LOADING = 'SET_USER_INFO_LOADING';
export const SET_USER_INFO_SUCCESS = 'SET_USER_INFO_SUCCESS';
export const SET_USER_INFO_FAIL = 'SET_USER_INFO_FAIL';
