export const ICON_WIDTH = '50%';

export const SELECTED_OPTIONS_KEYS = {
  NEW_TO_OLD: 'NEW_TO_OLD',
  OLD_TO_NEW: 'OLD_TO_NEW',
  CHEAP_TO_EXPENSIVE: 'CHEAP_TO_EXPENSIVE',
  EXPENSIVE_TO_CHEAP: 'EXPENSIVE_TO_CHEAP'
};
