export default {
  REQUEST_WISHLIST_LOADING: 'REQUEST_WISHLIST_LOADING',
  REQUEST_WISHLIST_SUCCESS: 'REQUEST_WISHLIST_SUCCESS',
  REQUEST_WISHLIST_FAIL: 'REQUEST_WISHLIST_FAIL',

  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  DELETE_FROM_WISHLIST: 'DELETE_FROM_WISHLIST'
};
