export default {
  SET_PRODUCT_INFO_STARTS: 'SET_PRODUCT_INFO_STARTS',
  SET_PRODUCT_INFO_SUCCESS: 'SET_PRODUCT_INFO_SUCCESS',
  SET_PRODUCT_INFO_FAIL: 'SET_PRODUCT_INFO_FAIL',

  ADD_FEEDBACK_TO_PRODUCT: 'ADD_FEEDBACK_TO_PRODUCT',
  REMOVE_FEEDBACK_FROM_PRODUCT: 'REMOVE_FEEDBACK_FROM_PRODUCT'
};
